spring:
  application:
    name: healthmonitor
  datasource:
    url: jdbc:postgresql://localhost:5432/healthdb?createDatabaseIfNotExist=true
    username: postgres
    password: postgre123
  jpa:
    show-sql: true